#!/usr/bin/env bash
# Verify that every Omarchy theme renders a valid Sway colour config through
# default/themed/sway.conf.tpl.
#
# Runs anywhere bash and git do -- including macOS, before the card is flashed.
#
#   ./scripts/test-themes.sh

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

. "$REPO_ROOT/scripts/manifest.sh"

# Read the pin rather than repeating it. This file carried its own copy, and
# when the branch moved to 4.0.2 it stayed on 3.8.4 -- so it fetched a theme set
# the phone does not install, rendered those, and passed. A check that measures
# something the device never sees is not a weaker check, it is a check that has
# stopped being one.
#
# It used to scrape the pin out of install/vendor-omarchy.sh, which worked but
# meant a second file had to know that one's syntax. Both read manifest.toml now.
PIN="${OMARCHY_PIN:-$(manifest_get omarchy ref)}"
[[ -n $PIN ]] || exit 1
URL="$(manifest_get omarchy url)" || exit 1

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

echo "==> fetching Omarchy at ${PIN:0:7}"
git clone --quiet --filter=blob:none --no-checkout \
  "$URL" "$WORK/omarchy"
git -C "$WORK/omarchy" checkout --quiet --detach "$PIN"

export OMARCHY_PATH="$WORK/omarchy"

# omarchy-theme-set-templates shells out to omarchy-theme-color for the whole
# colour table, so without the vendored bin/ on PATH it resolves nothing, every
# substitution is empty, and the template renders as if the theme had no colours
# -- silently, and with an exit status of 0.
export PATH="$OMARCHY_PATH/bin:$PATH"

# Omarchy 4.x builds its colour table in an associative array, which needs bash
# 4 or newer. macOS ships bash 3.2 as /bin/bash and these scripts hardcode that
# in their shebang, so PATH alone does not help: they would run under 3.2, fail
# with "declare: -A: invalid option", and render every colour as empty.
#
# So find a modern bash and put a wrapper in front of every omarchy script that
# asks for /bin/bash. Generated by scanning shebangs rather than naming the two
# scripts we happen to call today, so a future one is covered without anyone
# noticing it needed to be.
NEWBASH=""
for candidate in "$(command -v bash)" /opt/homebrew/bin/bash /opt/local/bin/bash /usr/local/bin/bash; do
  [[ -x $candidate ]] || continue
  if [[ $("$candidate" -c 'echo ${BASH_VERSINFO[0]}') -ge 4 ]]; then
    NEWBASH="$candidate"
    break
  fi
done

if [[ -z $NEWBASH ]]; then
  echo "==> needs bash 4 or newer to run Omarchy's theme scripts; found only $(/bin/bash --version | head -1)" >&2
  echo "    install one (brew install bash) and re-run" >&2
  exit 1
fi

SHIM="$WORK/shim"
mkdir -p "$SHIM"
for script in "$OMARCHY_PATH"/bin/*; do
  [[ -f $script ]] || continue
  head -1 "$script" | grep -q '^#!.*\bbash$' || continue
  printf '#!/bin/sh\nexec "%s" "%s" "$@"\n' "$NEWBASH" "$script" >"$SHIM/$(basename "$script")"
  chmod +x "$SHIM/$(basename "$script")"
done
export PATH="$SHIM:$PATH"

FAKE_HOME="$WORK/home"
mkdir -p "$FAKE_HOME/.config/omarchy/themed"
cp "$REPO_ROOT/default/themed/sway.conf.tpl" "$FAKE_HOME/.config/omarchy/themed/"

# 4.x writes the staged theme under .local/state, not .config. The old path is
# where 3.8.4 put it; pointed at that, the runner finds no colors.toml, does
# nothing at all, and leaves the test grepping a file that was never written.
NEXT_THEME="$FAKE_HOME/.local/state/omarchy/current/next-theme"

pass=0 fail=0

for theme in "$OMARCHY_PATH"/themes/*/; do
  name=$(basename "$theme")
  [[ -f $theme/colors.toml ]] || continue

  rm -rf "$NEXT_THEME"
  mkdir -p "$NEXT_THEME"
  cp "$theme/colors.toml" "$NEXT_THEME/"

  HOME="$FAKE_HOME" OMARCHY_PATH="$OMARCHY_PATH" \
    "$NEWBASH" "$OMARCHY_PATH/bin/omarchy-theme-set-templates"

  out="$NEXT_THEME/sway.conf"
  lines=$(grep -c '^client\.' "$out" 2>/dev/null || echo 0)
  malformed=$(grep '^client\.' "$out" 2>/dev/null |
    grep -vcE '^client\.[a-z_]+( +#[0-9a-fA-F]{6}){1,5} *$' || true)

  if [[ -f $out && $lines -eq 6 && ${malformed:-0} -eq 0 ]] && ! grep -q '{{' "$out"; then
    printf "  ok   %-18s accent=%s\n" "$name" "$(awk '/^client\.focused /{print $2}' "$out")"
    pass=$((pass + 1))
  else
    printf "  FAIL %-18s (client lines=%s malformed=%s)\n" "$name" "$lines" "${malformed:-0}"
    grep '{{' "$out" 2>/dev/null | head -2
    fail=$((fail + 1))
  fi
done

echo
echo "==> $pass passed, $fail failed"
(( fail == 0 ))
